# Generated by Django 5.0.6 on 2024-06-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
